const colorMapping = {
  Rød: 'Red',
  Blå: 'Blue',
  Grøn: 'Green',
  Gul: 'Yellow',
  Sort: 'Black',
  Hvid: 'White',
  Grå: 'Gray',
  Brun: 'Brown',
  Rosa: 'Pink',
  Lilla: 'Purple',
  Orange: 'Orange',
  Turkis: 'Turquoise',
  Beige: 'Beige',
  Mørkeblå: 'Dark Blue',
  Lyseblå: 'Light Blue',
  Mørkegrøn: 'Dark Green',
  Lysegrøn: 'Light Green',
  Mørkebrune: 'Dark Brown',
  Lyslilla: 'Light Purple',
  Koral: 'Coral',
  Cyan: 'Cyan',
  Magenta: 'Magenta',
  Indigo: 'Indigo',
  Guld: 'Gold',
  Sølv: 'Silver',
  Oliven: 'Olive',
  Sennep: 'Mustard',
  Kobber: 'Copper',
  Plomme: 'Plum',
  Himmelblå: 'Sky Blue',
  Havblå: 'Sea Blue',
  Kaki: 'Khaki',
  Mørkegrå: 'Dark Gray',
  Lysgrå: 'Light Gray',
  Aubergine: 'Aubergine',
  Mintgrøn: 'Mint Green',
  Hvidgrå: 'Off-White',
  'Café au Lait': 'Café au Lait',
  Sandal: 'Sand',
  Saffran: 'Saffron',
  Mørkerød: 'Dark Red',
  Havgrøn: 'Sea Green',
  Lysrosa: 'Light Pink',
  Smut: 'Teal',
  Guldgrøn: 'Gold Green',
  Periwinkle: 'Periwinkle',
  Lyslavendel: 'Light Lavender',
  Koboltblå: 'Cobalt Blue',
  Rahvid: 'Off White'
}

export default colorMapping
